### ISSUE TITLE
Swift 4, xcode 9 - there is no dayLabelingView

### ISSUE THREAD

**Issue by vladlo** [gservera/ScheduleKit#14]
<img width="1016" alt="screen shot 2017-09-29 at 1 07 51 pm" src="https://user-images.githubusercontent.com/20050977/31034097-734cf5f4-a517-11e7-841a-07523810ed0d.png">

**Comment by gservera** [comment]
Thank you for your issue report! I think I got rid of this by adding the dayLabelingView as subview to the scrollview's parent view instead of adding it to the scrollview directly. Please feel free to review the last commit and tell me if it worked for you!

**Comment by vladlo** [comment]
IT works! Thank you for fixing!
