### ISSUE TITLE
EventManager.m line 72: NSAssert("Should be ready") fails on OS Sierra

### ISSUE THREAD

**Issue by foolywk** [gservera/ScheduleKit#9]
A consistent crash on line 72 of EventManager.m `NSAssert(_ready, @"Should be ready")` on Mac OS Sierra while in dev. In release, the this seems to result in some buggy behavior on Sierra, such as  `SCKEventViews` not updating their size/position when zooming `SCKWeekView`.

**Comment by gservera** [comment]
Thank you! Fixed in the new release.
